name: IRONMAN demo

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      text:
        description: Enter text here
        type: string
        required: false
      reuse:
        description: Run reuse workflow?
        type: boolean

  #Allows this workflow to be called programatically as a downstream tasjk in another workflow
  workflow_call:
    inputs:
      text:
        description: Enter text here
        type: string
        required: false

jobs:
  cowsay:
    name: "The Cow Says:"
    runs-on: ironman

    steps:
      - uses: actions/checkout@v4

      - name: Report Hostname
        run: hostname

      - name: cowsay  
        if: ${{inputs.text}}
        run: cowsay ${{inputs.text}}

  weather:
    name: "How's the weather?"
    runs-on: ironman
    steps:
      - name: Run a multi-line script
        run: |
          curl wttr.in?format="%c+%l+%t+%m"
    
      - name: Get weather forecast
        run: curl wttr.in
  
  reuse:
    runs-on: ironman
    if: ${{inputs.reuse}}
    steps:
      - name: Run reuse if 
        run: cowsay "Reuse function selected... Running"
      
